// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"card\"><div class=\"card-header\"><h2>Please reach out to me here...</h2></div><div class=\"card-content\"><div class=\"contact-card\"><div class=\"contact-info\"><div class=\"contact-item\"><a href=\"tel:+7087399561\">Phone</a></div><div class=\"contact-item\"><a href=\"mailto:wy@willyoung.cloud\">Email</a></div><div class=\"contact-item\"><a href=\"https://www.github.com/es-codigo\" target=\"_blank\" rel=\"noopener noreferrer\">GitHub</a></div><div class=\"contact-item\"><a href=\"https://www.linkedin.com/in/will-young-sre\" target=\"_blank\" rel=\"noopener noreferrer\">LinkedIn</a></div></div><div class=\"contact-gif\"><img src=\"https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExYnNsdGVrdjRrcmFpazg0YjEwY2IybmZsb2thNWs1bGF0bHF4OWN6aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UFYD2rxZkTAaCBZ5VD/giphy.webp\" alt=\"Contact me\" class=\"w-[100%] h-auto\"></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
