// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Experience() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"section\"><h2 class=\"section-title\">PROFESSIONAL SUMMARY</h2><p>A professional summary stating your best-selling points based on the job description e.g. I am a Software Engineer with strong fundamentals in XXX looking to XXXX.</p></div><div class=\"section\"><h2 class=\"section-title\">WORK EXPERIENCE</h2><div class=\"list-item\"><div class=\"list-item-info\"><h3>Engineer I, American Express</h3><h3>Sep 2019 - Current</h3></div><ul><li>State your achievements at your role in this format: \"[Action verb] + what you did + reason, outcome or quantified results\".</li><li>Talk about technologies used.</li></ul></div><div class=\"list-item\"><div class=\"list-item-info\"><h3>Software Engineer, Polco</h3><h3>Aug 2019 - Dec 2019</h3></div><p>Built and refined React UI components, utilizing Storybook for isolated development and testing.</p><ul><li>React, Typescript, Jest, Node.Js, Knex and Storybook.</li></ul></div><div class=\"list-item\"><div class=\"list-item-info\"><h3>Frontend Web Developer, AATI</h3><h3>Jul 2018 - Jul 2019</h3></div><p>Developed and maintained a custom internal CRM with React for the owner to organize contacts to boost operations.</p><ul><li>CRM bootstrapped using create-react-app.</li><li>Successfully implemented email notifications to send invoices to customers using Stripe API.</li><li>Enabled a feature that allowed email marketing for upcoming destinations using Twilio SendGrid</li></ul></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
