// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "my-cloud-resume/components/ui"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"card\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.TitleBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"about\"><div class=\"about-images\"><img src=\"https://storage.googleapis.com/my-cloud-resume-images/HeadshotBig.jpg\" alt=\"William Young\" class=\"profile-image\"> <img src=\"https://storage.googleapis.com/my-cloud-resume-images/egypt.jpg\" alt=\"William in Egypt\" class=\"profile-image\"></div><div class=\"bio\"><h2>About Me</h2><p>I'm a world traveler with a passion for exploring new cultures and cuisines (ask me about the time I ate a bug while visiting “La Casa del Suizo” in Ecuador). When I'm not jet-setting, you'll find me immersed in the virtual worlds of video games or perfecting my BBQ skills on the patio. I also enjoy unwinding with a good anime (One Piece is my current obsession).  </p><h3>Ambitions</h3><ul><li>One Career Ambition is to reach at least Staff Engineer level</li><li>Own 40+ acres of land for my family's compound </li><li>Start an Indie Video Game company I already have a few ideas written down</li></ul></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
