// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "my-cloud-resume/components/ui"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"card\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.TitleBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"about\"><div class=\"about-images\"><img src=\"https://storage.googleapis.com/my-cloud-resume-images/HeadshotBig.jpg\" alt=\"William Young\" class=\"profile-image\"> <img src=\"https://storage.googleapis.com/my-cloud-resume-images/egypt.jpg\" alt=\"William in Egypt\" class=\"profile-image\"></div><div class=\"bio\"><h2>About Me</h2><p>I am a software engineer with a passion for cloud technologies and observability. I have experience with a variety of programming languages and tools, including Go, JavaScript, HTML, CSS, Docker, and Postgres. I have also worked with cloud technologies such as AWS, GCP, Azure, Kubernetes, and Terraform. I have experience with observability and logging tools such as Prometheus, Grafana, and Splunk.</p><p>I am a software engineer with a passion for cloud technologies and observability. I have experience with a variety of programming languages and tools, including Go, JavaScript, HTML, CSS, Docker, and Postgres. I have also worked with cloud technologies such as AWS, GCP, Azure, Kubernetes, and Terraform. I have experience with observability and logging tools such as Prometheus, Grafana, and Splunk.</p><p>I am currently working as a software engineer at a cloud technology company. I am excited to continue learning and growing in my career, and I am always looking for new opportunities to expand my skills and knowledge.</p><p>I am currently working as a software engineer at a cloud technology company. I am excited to continue learning and growing in my career, and I am always looking for new opportunities to expand my skills and knowledge.</p><h3>Ambitions</h3><ul><li>Learn more about cloud technologies and observability</li><li>Contribute to open-source projects</li><li>Continue to grow and develop as a software engineer</li></ul></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
