// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ContactStyles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n    /* Contact Page Styles */\n        .contact-card {\n            display: flex;\n            flex-direction: column;\n            gap: 1rem;\n            font-size: 1.5rem;\n            padding: 0 5rem 0 5rem;\n            align-items: center;\n            font-weight: 800;\n            color: white;\n    \n        }\n\n        .contact-card a{\n            color: #5af78e;\n            text-decoration: none ;\n        }\n\n\n        .contact-info {\n            display: flex;\n            flex-direction: row;\n            gap: 1rem;\n        }\n\n        @media (max-width: 500px) {\n            #contact.card-header {\n                padding: 1.5rem\n            }   \n            #contact.contact-header h2 {\n                font-size: 1.5rem;\n            }\n\n            .contact-info {\n                flex-direction: column;\n                gap: 1rem;\n            }\n\n            .contact-gif img {\n               width: 20rem;\n            };\n        }\n\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
