// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func NavbarStyles() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n.navbar {\n    background-color: #333;\n    position: fixed;\n    top: 0;\n    left: 0;\n    width: 100%;\n    z-index: 100;\n    padding: 1rem;\n    box-shadow: 0 10px 20px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);\n    font-weight: 700;\n}\n\n\n.logo {\n    max-width:200px;\n    height: auto;\n}\n\n\n.navbar-content {\n    display: flex;\n    justify-content: space-around;\n    align-items: center;\n    max-width: 100vw;\n    margin: 0 auto;\n}\n\n\n.hamburger-menu {\n    display: none;\n}\n\n.hamburger-label {\n    display: none;\n    cursor: pointer;\n    padding: 10px;\n}\n\n.hamburger-label span {\n    display: block;\n    width: 25px;\n    height: 3px;\n    background-color: white;\n    margin-bottom: 5px;\n    transition: 0.3s;\n}\n\n.nav-items {\n    display: flex;\n    gap: 1rem;\n}\n\n.nav-item {\n    color: white;\n    text-decoration: none;\n    transition: color 0.3s;\n}\n\n.nav-item:hover {\n    color: #ddd;\n}\n\n@media (max-width: 960px) {\n    .hamburger-label {\n        display: block;\n    }\n\n    .nav-items {\n        display: none;\n        flex-direction: column;\n        position: absolute;\n        top: 70px;\n        left: 0;\n        right: 0;\n        background-color: #333;\n        padding: 1rem;\n    }\n\n    .hamburger-menu:checked ~ .nav-items {\n        display: flex;\n    }\n\n    .nav-item {\n        padding: 0.5rem 0;\n        cursor: pointer;\n    }\n\n    .hamburger-menu:checked ~ .hamburger-label span:nth-child(1) {\n        transform: rotate(-45deg) translate(-5px, 6px);\n    }\n\n    .hamburger-menu:checked ~ .hamburger-label span:nth-child(2) {\n        opacity: 0;\n    }\n\n    .hamburger-menu:checked ~ .hamburger-label span:nth-child(3) {\n        transform: rotate(45deg) translate(-5px, -6px);\n    }\n\n\n}\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
